<!DOCTYPE html>
<html>
<head>
	<title>Css Demo</title>
	<link rel="stylesheet" type="text/css" href="style1.css">
</head>
<body>

<a href="css.php">Link</a>	

<ol>
	<li> Item 1 </li>
	<li>Item 2</li>
	<li>Item 3</li>
</ol>	
	

<div id="div1">
	 
	<a href="#">click</a>

</div>	

<br>
	<div>
	<span class="cls">span content</span>
	div 1 div 1 div 1 
	div 1 div 1 div 1 
	div 1 div 1 div 1 
	div 1 div 1 div 1 
	div 1 div 1 div 1
	asdasdasd 
	asdasdasd 
	
	</div>
	<div>div 2</div>
	<div id="div3">div 3</div>

<br>

<p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p>
<p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p>
<p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p><p>asdasd</p>


</body>
</html>